version: "3.7"
services:
  app:
    build:
      args:
        user: issue-tracker
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: issue-tracker
    container_name: issue-tracker-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./issue-tracker/:/var/www
    networks:
      - issue-tracker

  nginx:
    image: nginx:alpine
    container_name: issue-tracker-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./issue-tracker/:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - issue-tracker

  mysql8.0:
    image: mysql:8.0
    container_name: issue-tracker-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracker
    volumes:
      - ./.docker/db/:/var/lib/mysql
    ports:
      - 3366:3306
    networks:
      - issue-tracker       

networks:
  issue-tracker:
    driver: bridge
